// <auto-generated />
using financa_repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace financa_repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171114170959_DespesasMigrations")]
    partial class DespesasMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("financa_domain.Despesa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataDespesa");

                    b.Property<string>("estabelecimento");

                    b.Property<int?>("grupoDespesaid");

                    b.Property<string>("numDoc");

                    b.Property<double>("valor");

                    b.HasKey("id");

                    b.HasIndex("grupoDespesaid");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("financa_domain.TipoDespesa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("TiposDespesas");
                });

            modelBuilder.Entity("financa_domain.Despesa", b =>
                {
                    b.HasOne("financa_domain.TipoDespesa", "grupoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("grupoDespesaid");
                });
#pragma warning restore 612, 618
        }
    }
}
